### ISSUE TITLE
How to load non-uniform density of the species in VPIC

### ISSUE THREAD

**Issue by rataniitb** [lanl/vpic#104]
Hi,

I need to specify a non-uniform plasma density for my VPIC study. How to specify a linear density ramp in VPIC in x- direction ? 

Please help me. Thanks. 

Regards,

Ratan

**Comment by rfbird** [comment]
Hey, 

The easiest way to do this is to increase the number of particles you place in each cell during user initialization, in your input deck. This may lead to some load imbalance, depending on how large a density gradient you need. 

Best,
Bob
