### ISSUE TITLE
Input deck: electric field inside set_region_field does not work?

### ISSUE THREAD

**Issue by alkinkaz** [lanl/vpic#111]
Hi, I am just a newbie learning how to use this code and I want to be able to introduce electric field into my simulation. In order to do that, I included `set_region_field` inside `begin_initialization` and tried to add some magnetic and electric fields. Magnetic fields worked well but there is no electric field (as I see from the Paraview visualizations). Later I tried to understand and use `field(ix, iy, iz)` (the declaration is at `./src/vpic.h` line 290) but I couldn't understand what these parameters meant and how to use them. Any help will be appreciated!

Correction: the declaration seems to be at `./src/field_advance/standard/remote.c` line 15

**Comment by rfbird** [comment]
Hey,

The line you link to :

```
#define field(x,y,z) field[ VOXEL(x,y,z, nx,ny,nz) ]
```

What this does is change the 3d index you pass it `(x/y/z)` from a human readable form to the 1d form the code uses internally. From a user perspective you can just use the 3d form as `field(x,y,z)`

`set_region_field` should respect your request for both electric and magnetic field

**Comment by alkinkaz** [comment]
Thanks - so, in order to introduce some external fields **E**(**r**, t) and **B**(**r**, t), do I need to use `set_region_field()` inside the `begin_field_injection` part of the input deck? In some of the sample decks, I saw this `field(ix, iy, iz)` function being used (e.g. `./sample/lpi_2d_F6_test` line 957) and I couldn't understand which function should be used how for my goal in introducing electromagnetic fields to the simulation.

**Comment by rfbird** [comment]
I don't think you want to do `set_region_field` inside `begin_field_injection`, that would give you a fixed field every time step. If you want an initial EM field then doing `set_region_field` in `user_initialization` seems to be the right thing to do

`field(ix,iy,iz)` lets the expert user manually write field values directly

**Comment by alkinkaz** [comment]
Thanks, now I understand the function `set_region_field` and I was able to initiate some electric field in my simulation. But in my simulations, our experiment has RF antennas and I will need the simulation to take those fields into account through the simulation as well as the internal fields in plasma. I believe that there were some examples of current injection as well, but it was not clear for me about how I should proceed. How can I learn more about `field(ix, iy, iz)` is used? Does it also work in the same way as `set_region_field`, or does it have different functionalities?

**Comment by petschge** [comment]
Antennas are often modeled by adding the current inside the antenna to a single grid point instead of setting fields. The latter would be known as a "hard source". Have a look at `sample/dipole`. The `jfz` it sets is the z component of the free current.

**Comment by alkinkaz** [comment]
@petschge thanks, I took a look into it and I believe I understood the function - I assume the input parameter numbers `field(33,33,32).jfz` means that we make the specific cell `(33, 33, 32)` have this current? Please correct me if I am wrong.

**Comment by petschge** [comment]
That is correct. Consider that cell ix,iy,iz extends from (ix-1)*dx to ix*dx, from (iy-1)*dy to iy*dy and from (iz-1)*dz to iz*dz. (Cells with index 0 are ghost cells outside the domain). Also consider that jfz of cell ix,iy,iz is located at ix*dx, iy*dy, (iz+0.5)*dz due to the staggered grid. That implies that field(33,33,32).jfz is as close to the center of the 64x64x64 domain as possible.

**Comment by alkinkaz** [comment]
Thanks for the help, I really appreciate it! I am now closing the issue.
