### ISSUE TITLE
the tutorial about the vpic data

### ISSUE THREAD

**Issue by wangzhezhe** [lanl/vpic#134]
Hello, 
 
I could compile the vpic and execute the sample application based on readme, where could I get further information such as how to visualize the simulation data base on paraview and more details about the vpic data?

Thanks a lot for your help!

**Comment by rfbird** [comment]
Hi,

Thanks for your question. I'll provide some details below, but also check out: https://github.com/lanl/vpic/issues/94 #94 

There is sadly not a tutorial (per se), but the python scripts in the above issue are a good starting place to figuring out how to read the data output from VPIC

We are also working on an HDF5 backend which will make this much simpler for users, but that does not currently support fine grained output support

**Comment by wangzhezhe** [comment]
Thanks !
