### ISSUE TITLE
inbound license for contributions

### ISSUE THREAD

**Issue by jlovejoy** [lanl/vpic#15]
Can you confirm that contributions to the project are licensed inbound to the project under the same license as the outbound license? 

thanks

**Comment by rfbird** [comment]
I'll seek out an official answer to this. Is there anything specific you're concerned about?

In the mean time you may find it useful to look at a contributor agreement for a similarly licensed LANL project: https://github.com/laristra/flecsi/blob/master/CONTRIBUTING.md

**Comment by jlovejoy** [comment]
no concern, just wanted to make sure we know what license we are contributing under. If there is not an explicit statement otherwise (e.g., reference to a CLA in the specific repository), we tend to assume it's inbound=outbound, but always good to check!

**Comment by rfbird** [comment]
OK, let me know if you want to address this in more detail and we can find out via legal

**Comment by rfbird** [comment]
To follow up on this, here is the contribution agreement one should sign before contributing: https://www.clahub.com/agreements/losalamos/vpic
