### ISSUE TITLE
user manual

### ISSUE THREAD

**Issue by masoudjon** [lanl/vpic#21]
Hello,

Dear developers, I have two questions:

1- as far as I know the VPIC code is open source so every Body can use it? is it correct.?
2- is there any Manual which I can read to understand how to create an Input file

thanks in advance
masoud

**Comment by rfbird** [comment]
Hey Masoud,

1. Yes, VPIC is open-source, and absolutely free for everyone to use. (There is a copyright notice in the readme which covers redistribution)
2. Sadly, there is currently no comprehensive input decks. We provide many examples (with comments) in the ./sample. Please note anything labelled 407 is legacy and included only as reference. 

Best,
Bob
