### ISSUE TITLE
epic data analysis

### ISSUE THREAD

**Issue by dsbertini** [lanl/vpic#23]
Hi
Is there a description of native VPIC format that one can use to read/visualize data from let's say a
home written python script instead of Paraview  ?
Thanks in advance
Denis

**Comment by rfbird** [comment]
Hey,

This is an on-going question for us right now. 

We're currently reviewing the current output format, as we're aware it's not ideal. Especially as there is little reason not to use a more standardized format. 

Some users do use python (and other things, like IDL) for vis. Typically what they do is first convert the output files to a different format, and then work with that. 

There's definitely nothing stopping you working with the native format directly. The data that is dumped is often input deck dependent, and as such it's hard to give a good description of the file format (lame, I know, sorry).

Which fields/quantities are you interested in? If you look in the harris deck (`./sample/harris`), you can see the various `dump_***` calls, most of which are defined in `./src/vpic/dump.cc`. You can see there for how each thing is dumped

Something we would like to do is have a standard example of how to read these, if you come up with a python script to do so we'd love to incorporate it into the repo as an example to other users 

Best,
Bob

**Comment by rfbird** [comment]
Hey,

Is this still an issue for you? Did you figure it out or would a small example be useful to you?

Best,
Bob

**Comment by jimgreen** [comment]
I use Python to direct parse output from the GEM problem deck. But various assumptions based on this particular deck, so I am not sure how well it would work for other problems.

Here is a demo:
https://gist.github.com/jimgreen/a57bf24d1bb3f91388b2ca6e91802edf

**Comment by jimgreen** [comment]
As for the output format itself, perhaps it is easier (from a user's perspective) to go widely used standards like HDF5 or ADIOS.

**Comment by rfbird** [comment]
Hey,

Thanks for the replies @jimgreen, very helpful.

We're definitely considering the move to HDF5, but right now are unsure we have the developer effort to commit to it.

I think the python example posted is really useful. As you noted it's hard to publish a cookie-cutter example as it's deck output specific.

I'm going to close this issue for now, but I think it's a fantastic reference for users

Best,
Bob
