### ISSUE TITLE
Example laser thin target interaction ?

### ISSUE THREAD

**Issue by dsbertini** [lanl/vpic#24]
Hi 
Is there some VPIC input example describing the interaction of a high-intensity 
laser with a solid target ?

**Comment by rfbird** [comment]
Hey,

We don't have any sample decks like that right now. The decks we do have are in `./sample/` (code pulled directly from anything labelled `407` will need some modifications). They should hopefully contain most of the building blocks you need to get started. If you run into specific issues, feel free to let us know also

Best,
Bob
