### ISSUE TITLE
Issues with child_langmuir emitter after particle boundary interaction

### ISSUE THREAD

**Issue by astanier** [lanl/vpic#27]
The child langmuir emitter moves newly emitted and 'aged' particles by calling the particle mover as:
        pm[nm].disp##X = w*u##X*rd##X;                                  \
        pm[nm].disp##Y = w*u##Y*rd##Y;                                  \
        pm[nm].disp##Z = w*u##Z*rd##Z;                                  \
        pm[nm].i       = np-1;                                          \
        nm += move_p( p, pm, a, g, qsp );                               \

However, if a particle already had a boundary interaction in 'advance_p' it is at the top of the 'pm' list. The call of move_p in the emitter code then attempts to move the already out of bounds particle, instead of the newly emitted particle as intended.

This can be fixed by using a local particle mover, as is used in 'advance_p'. That is:

 DECLARE_ALIGNED_ARRAY( particle_mover_t, 16, local_pm, 1 );
...
        local_pm->disp##X = w*u##X*rd##X;                                  \
        local_pm->disp##Y = w*u##Y*rd##Y;                                  \
        local_pm->disp##Z = w*u##Z*rd##Z;                                  \
        local_pm->i       = np-1;                                          \
       if ( move_p( p, local_pm, a, g, qsp ) ) {                       \
          pm[nm++] = local_pm[0];                                       \
        }

**Comment by rfbird** [comment]
Well...that's not good! 

I'll look into this, is the fix as simple as just adding the if like you describe? No secret physics side-affects? Have you run with the fixed version? 

If so, looks simple enough to apply so can fix ASAP

**Comment by rfbird** [comment]
As per Adam's email: 

> I haven’t seen any problems with the changes so far.
> 
> I attached an updated version of the ‘sample/emission’ deck for which you can see the problem (the deck in the repo does not work for setting up the grid & does nothing).
> 
> When I try to run it on 2 processors with the ‘absorbing_particles’ BC I get a backtrace pretty quickly. This is fixed if you run with the changes mentioned.

I think this is a good fix, I'll prepare and merge it.
