### ISSUE TITLE
Issues restarting in v1.1 -- globals not loaded

### ISSUE THREAD

**Issue by jonngwx** [lanl/vpic#57]
When restarting in 1.1, global variables are initialised to 0. This affects decks which use the globals (e.g. sample/harris doesn't write output after restarting, sample/asymm4sp crashes due to division by zero when checking restart_interval)

I believe it's related to this change:
https://github.com/lanl/vpic/pull/48
Should decks be modified not to use globals or is there a way to store them?

**Comment by rfbird** [comment]
Yes, my apologies, you're absolutely right. 

I also bumped into something that presents like this earlier in the week, and was hoping to find a more elegant solution. I'll roll back the changes in #48
