### ISSUE TITLE
RelayPolicy will not build for MPWrapper

### ISSUE THREAD

**Issue by mkuchnik** [lanl/vpic#8]
src/util/mp/MPWrapper.h is a wrapper around DMPPolicy or RelayPolicy, depending on configuration. RelayPolicy is not a valid build as it is missing its include dependencies (e.g. ConnectionManager.h, P2PConnection.h, checkpt.h).

**Comment by rfbird** [comment]
We hard need MPI to build, so we're punting on this (but agree it should be improved at some point)
