### ISSUE TITLE
GPU version

### ISSUE THREAD

**Issue by eee4017** [lanl/vpic#86]
Hi,

We modified some of the code and it supports GPU acceleration. We are not sure whether this is helpful or not. You could check it out.

https://github.com/eee4017/vpic-GPU

**Comment by rfbird** [comment]
Hey Frank,

It was really great chatting to you and the rest of the team at SC, well done again for all the great work at the student cluster competition, I was really impressed.

Thanks for sending us the GPU code, I look forward to reading over it

Best,
Bob
